# Generated by Django 3.2.4 on 2021-09-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nutriscore', models.CharField(max_length=1)),
                ('key_100g', models.TextField()),
                ('url', models.URLField()),
                ('imgurl', models.URLField(null=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='categories', to='substitutes.Categories')),
                ('stores', models.ManyToManyField(blank=True, related_name='stores', to='substitutes.Stores')),
            ],
        ),
    ]
