# Generated by Django 3.2.4 on 2021-07-12 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nutriscore', models.CharField(max_length=1)),
                ('ingredients', models.TextField()),
                ('url', models.URLField()),
                ('categories', models.ManyToManyField(blank=True, related_name='categories', to='substitutes.Categories')),
                ('stores', models.ManyToManyField(blank=True, related_name='stores', to='substitutes.Stores')),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='substitutes.product')),
            ],
        ),
    ]
