# Generated by Django 3.2.4 on 2021-08-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210806_1451'),
        ('substitutes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imgurl',
            field=models.URLField(null=True),
        ),
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
