# Generated by Django 3.2.4 on 2021-09-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitutes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
