# Generated by Django 3.2.4 on 2021-08-16 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('substitutes', '0002_auto_20210816_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ingredients',
            new_name='key_100g',
        ),
    ]
