# Generated by Django 3.2.4 on 2021-09-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitutes', '0002_alter_categories_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutriments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='stores',
        ),
        migrations.DeleteModel(
            name='Stores',
        ),
        migrations.AddField(
            model_name='product',
            name='nutriments',
            field=models.ManyToManyField(blank=True, related_name='stores', to='substitutes.Nutriments'),
        ),
    ]
