# Generated by Django 3.2.4 on 2021-09-28 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("substitutes", "0004_alter_product_nutriments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="key_100g",
        ),
    ]
