# Generated by Django 3.2.4 on 2021-10-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitutes', '0005_remove_product_key_100g'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutriments',
            name='value',
            field=models.IntegerField(null=True),
        ),
    ]
