# Generated by Django 3.2.4 on 2021-11-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitutes', '0007_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
