# Generated by Django 3.2.4 on 2021-08-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitutes', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='start_date',
            new_name='registration_date',
        ),
        migrations.AddField(
            model_name='newuser',
            name='favorites',
            field=models.ManyToManyField(to='substitutes.Favorites'),
        ),
    ]
