# Generated by Django 3.2.4 on 2021-08-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitutes', '0002_auto_20210816_1659'),
        ('users', '0002_auto_20210806_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorites', to='substitutes.Product'),
        ),
    ]
